# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_task_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(422, 192)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.taskName = QtWidgets.QLineEdit(Dialog)
        self.taskName.setObjectName("taskName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.taskName)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.optimisticTime = QtWidgets.QDoubleSpinBox(Dialog)
        self.optimisticTime.setDecimals(3)
        self.optimisticTime.setMinimum(0.0)
        self.optimisticTime.setMaximum(10000.0)
        self.optimisticTime.setObjectName("optimisticTime")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.optimisticTime)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.realisticTime = QtWidgets.QDoubleSpinBox(Dialog)
        self.realisticTime.setDecimals(3)
        self.realisticTime.setMinimum(0.0)
        self.realisticTime.setMaximum(10000.0)
        self.realisticTime.setObjectName("realisticTime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.realisticTime)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pessimisticTime = QtWidgets.QDoubleSpinBox(Dialog)
        self.pessimisticTime.setDecimals(3)
        self.pessimisticTime.setMinimum(0.0)
        self.pessimisticTime.setMaximum(10000.0)
        self.pessimisticTime.setObjectName("pessimisticTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pessimisticTime)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.taskName)
        self.label_2.setBuddy(self.optimisticTime)
        self.label_3.setBuddy(self.realisticTime)
        self.label_4.setBuddy(self.pessimisticTime)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Task"))
        self.label.setText(_translate("Dialog", "&Task:"))
        self.label_2.setText(_translate("Dialog", "&Optimistic time: "))
        self.label_3.setText(_translate("Dialog", "&Most Likely time:"))
        self.label_4.setText(_translate("Dialog", "&Pessimistic:"))
