# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_task_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditDialog(object):
    def setupUi(self, EditDialog):
        EditDialog.setObjectName("EditDialog")
        EditDialog.resize(427, 188)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(EditDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.taskName_2 = QtWidgets.QLineEdit(EditDialog)
        self.taskName_2.setObjectName("taskName_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.taskName_2)
        self.label_6 = QtWidgets.QLabel(EditDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.optimisticTime_2 = QtWidgets.QDoubleSpinBox(EditDialog)
        self.optimisticTime_2.setDecimals(3)
        self.optimisticTime_2.setMinimum(0.0)
        self.optimisticTime_2.setMaximum(10000.0)
        self.optimisticTime_2.setObjectName("optimisticTime_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.optimisticTime_2)
        self.label_7 = QtWidgets.QLabel(EditDialog)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.realisticTime_2 = QtWidgets.QDoubleSpinBox(EditDialog)
        self.realisticTime_2.setDecimals(3)
        self.realisticTime_2.setMinimum(0.0)
        self.realisticTime_2.setMaximum(10000.0)
        self.realisticTime_2.setObjectName("realisticTime_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.realisticTime_2)
        self.label_8 = QtWidgets.QLabel(EditDialog)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.pessimisticTime_2 = QtWidgets.QDoubleSpinBox(EditDialog)
        self.pessimisticTime_2.setDecimals(3)
        self.pessimisticTime_2.setMinimum(0.0)
        self.pessimisticTime_2.setMaximum(10000.0)
        self.pessimisticTime_2.setObjectName("pessimisticTime_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pessimisticTime_2)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_5.setBuddy(self.taskName_2)
        self.label_6.setBuddy(self.optimisticTime_2)
        self.label_7.setBuddy(self.realisticTime_2)
        self.label_8.setBuddy(self.pessimisticTime_2)

        self.retranslateUi(EditDialog)
        self.buttonBox.accepted.connect(EditDialog.accept)
        self.buttonBox.rejected.connect(EditDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EditDialog)

    def retranslateUi(self, EditDialog):
        _translate = QtCore.QCoreApplication.translate
        EditDialog.setWindowTitle(_translate("EditDialog", "Edit Task"))
        self.label_5.setText(_translate("EditDialog", "&Task:"))
        self.label_6.setText(_translate("EditDialog", "&Optimistic time: "))
        self.label_7.setText(_translate("EditDialog", "&Most Likely time:"))
        self.label_8.setText(_translate("EditDialog", "&Pessimistic:"))
